---
  rules:
    indent:
      - 2
      - 4
      -
        SwitchCase: 1
    quotes:
      - 2
      - "single"
    semi:
      - 2
      - "always"
    react/jsx-uses-react: 1
    no-console: 0
  env:
    es6: true
    browser: true
  extends: "eslint:recommended"
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
    modules: true
  plugins:
    - "react"
  globals:
     /* mocha */
    describe: true
    it: true
    before: true
    after: true
    beforeEach: true
    afterEach: true
    /* chai */
    expect: true
    assert: true
    /* sinon */
    sinon: true
    module: true
